### ISSUE TITLE
URL Length

### ISSUE THREAD

**Issue by gordonkristan** [gordonkristan/ember-graph#66]
The built-in REST adapter doesn't put a limit on URL lengths, causing bugs in some browsers. We should keep the URLs below 2,000 characters.

**Comment by mtheoryx** [comment]
I've seen this where we have a predominantly GUID-based app, and there are GET requests that are over 6,000 characters in length.

 Not sure if this is related, but it can cause issues on the server side for sure.

**Comment by gordonkristan** [comment]
I might be able to get to this tonight. It should be a pretty easy to cover most cases.

**Comment by gordonkristan** [comment]
Should be good to go. :+1: I'm having some issues with the builds being uploaded to S3 though. I'll look into that now, but you might need to host the files elsewhere in the meantime.

**Comment by mtheoryx** [comment]
Brilliant solution, thank you!
