### ISSUE TITLE
API docs are 404 on github

### ISSUE THREAD

**Issue by mtheoryx** [gordonkristan/ember-graph#70]
Not sure what happened but the gh-pages branch is down:

http://ember-graph.com/

**Comment by gordonkristan** [comment]
Nice catch, I updated the Node version in `package.json` but not in `.travis.yml`. Wait for [this build](https://travis-ci.org/gordonkristan/ember-graph/builds/62417982) to finish and you should be good to go.

**Comment by mtheoryx** [comment]
Thanks Gordon!
