### ISSUE TITLE
Mixing JSON API data with mocked fixture data

### ISSUE THREAD

**Issue by mtheoryx** [gordonkristan/ember-graph#74]
I tried to use a per-model LocalStorageAdapter to load in some fixture data so I can work on the client while the API development catches up.

The adapter for this model is below:

```javascript
let RiskMatrixAdapter = EG.LocalStorageAdapter.extend({

	getInitialPayload: function() {
		return {
			riskMatrix: [{
				id: 0,
				project: 'cf4961ed-3f3f-4a07-bb08-9f4823c99af9',
				riskLevelMatrix: 0,
				riskBands: []
			}]
		};
	}
});

export default RiskMatrixAdapter;
```

Nothing gets loaded into the store or localstorage.

Is there any way to use fixture data for server-less development with EG? The methods I found for Ember Data do not work (adding reopenClass in the model, and I'd have to use the ember data fixture adapter as well).

**Comment by hamiltondanielb** [comment]
Can you not reopen the model itself like 

```
export default DS.Model.extend({
  	name: DS.attr('String'),
	wins: DS.attr('Number'),
	losses: DS.attr('Number'),
	email: DS.attr('String')
}).reopenClass({
    FIXTURES: [
        {
            id: 1,
            name: "Dan Hamilton",
            wins: 7,
            losses: 6
        },
        {
            id: 2,
            name: "Joel Norman",
            wins: 2,
            losses: 10
        },
        {
            id: 3,
            name: "Nick Tippmann",
            wins: 15,
            losses: 5
        }
    ]
```

**Comment by mtheoryx** [comment]
Correct, that doesn't seem to do anything that I can tell. I think the big issue is that the project object is NOT provided by fixture data. That could be the line that I can't reconcile when mixing fixture and non-fixture data.

```javascript
import BaseModel from './base';

const RiskMatrix =  BaseModel.extend({

	project: EG.hasOne({
		relatedType: 'project',
		inverse: 'riskMatrix',
		readOnly: true
	}),

	riskLevelMatrix: EG.hasOne({
		relatedType: 'riskLevelMatrix',
		inverse: 'riskMatrix',
		isRequired: false
	}),

	riskBands: EG.hasMany({
		relatedType: 'riskBand',
		inverse: 'riskMatrix',
		isRequired: false
	})
});

RiskMatrix.reopenClass({
	FIXTURES: [
		{
			id: 0,
			project: 'cf4961ed-3f3f-4a07-bb08-9f4823c99af9',
			riskLevelMatrix: 0,
			riskBands: []
		}
	]
});

export default RiskMatrix;
```

Each of several new models have this fixture data. 

But for example, I cannot even issue a simple store.find('riskMatrix', 0) which I would think would get me this fixture; it results in a "A bad `find` call was made to the store" error.

**Comment by gordonkristan** [comment]
Well the bad find call is because it looks like you tried to pass a number to the store as an ID. Ember Graph uses strings for IDs. There are a few places where numbers _might_ work because of coercion, but 99% of the time it will complain about them (I hate weak typing).

As for data not being loaded, are you overriding the [shouldInitializeDatabase](http://ember-graph.com/api/LocalStorageAdapter.html#method_shouldInitializeDatabase) hook? By default it always returns `false`. (The idea behind that hook is that you likely don't want to clear the local storage every time you refresh the page. It allows you to implement more advanced initialization logic.)

**Comment by gordonkristan** [comment]
Also, I should mention that mixing data source should be fine. When a record (or set of records) is requested from the store, it does a lookup to determine which adapter needs to be used to get that data. Just make sure that the ID you use in the local storage data corresponds to an actual ID in the database.

**Comment by mtheoryx** [comment]
Okay, so here's my model (I took out the reopenClass, it doesn't work either way):

```javascript
import BaseModel from './base';

const RiskMatrix =  BaseModel.extend({

	project: EG.hasOne({
		relatedType: 'project',
		inverse: 'riskMatrix',
		readOnly: true,
		isRequired: false
	}),

	riskLevelMatrix: EG.hasOne({
		relatedType: 'riskLevelMatrix',
		inverse: 'riskMatrix',
		isRequired: false
	}),

	riskBands: EG.hasMany({
		relatedType: 'riskBand',
		inverse: 'riskMatrix',
		isRequired: false
	})
});

//RiskMatrix.reopenClass({
//	FIXTURES: [
//		{
//			id: '0',
//			project: 'cf4961ed-3f3f-4a07-bb08-9f4823c99af9',
//			riskLevelMatrix: '0',
//			riskBands: []
//		}
//	]
//});

export default RiskMatrix;
```

Here is my adapter:

```javascript
let RiskMatrixAdapter = EG.LocalStorageAdapter.extend({

	shouldInitializeDatabase: function () {
		return true;
	},

	getInitialPayload: function() {
		return {
			riskMatrix: [{
				id: '0',
				project: 'cf4961ed-3f3f-4a07-bb08-9f4823c99af9',
				riskLevelMatrix: '0',
				riskBands: []
			}]
		};
	}
});

export default RiskMatrixAdapter;
```

And here in a controller, I'm just trying to get that one riskMatrix:

```javascript
findRiskMatrix: function () {
		const riskMatrices = Session.store.find('riskMatrix', '0');
		console.log(riskMatrices);
	}.on('init'),
```

Here is the error I get, and the line it happens on:

TypeError: Cannot read property 'cf4961ed-3f3f-4a07-bb08-9f4823c99af9' of undefined
    at https://local.greenlight.guru:8000/lib/ember-graph/ember-graph.js:2672:36
    at Array.forEach (native)
    at EG.EmberGraphAdapter.reopen.validateDatabase (https://local.greenlight.guru:8000/lib/ember-graph/ember-graph.js:2667:11)
    at EG.EmberGraphAdapter.reopen.convertAndVerifyPayload (https://local.greenlight.guru:8000/lib/ember-graph/ember-graph.js:2503:8)
    at EG.EmberGraphAdapter.reopen.initializeDatabase (https://local.greenlight.guru:8000/lib/ember-graph/ember-graph.js:2482:18)
    at apply (https://local.greenlight.guru:8000/lib/ember/ember.js:19671:32)
    at superFunction [as _super] (https://local.greenlight.guru:8000/lib/ember/ember.js:16103:15)
    at EG.LocalStorageAdapter.EG.EmberGraphAdapter.extend.initializeDatabase (https://local.greenlight.guru:8000/lib/ember-graph/ember-graph.js:2938:8)
    at apply (https://local.greenlight.guru:8000/lib/ember/ember.js:19671:32)
    at superWrapper [as initializeDatabase] (https://local.greenlight.guru:8000/lib/ember/ember.js:19245:15)

In validateDatabase function:

```javscript
if (!db.records[relationship.t2][relationship.i2]) {
    throw new Em.Error(relationship.t2 + ':' + relationship.i2 + ' doesn\'t exist');
}
```

**Comment by gordonkristan** [comment]
It's all coming back to me now. :stuck_out_tongue: The `EmberGraphAdapter` (which `LocalStorageAdapter` extends) expects a complete database to be loaded. This is because it manages _all_ of the data for that database, including relationships. You may not be able to use the `LocalStorageAdapter` for this purpose. However, it wouldn't be very hard to write an adapter from scratch to do some basic loading.

```js
// These objects should look like what you would get in a server response
// The serializer will do all of the conversions and insert default values
const RiskMatrixData = {
	'0': {
		id: '0',
		links: {
			project: 'cf4961ed-3f3f-4a07-bb08-9f4823c99af9',
			riskLevelMatrix: '0',
			riskBands: []
		}
	}
};

const RiskMatrixAdapter = EmberGraph.Adapter.extend({
	findRecord(typeKey, id) {
		const payload = {
			riskMatrices: [RiskMatrixData[id]]
		};

		const normalizedPayload = this.deserialize(payload, { requestType: 'findRecord', recordType: typeKey, id });

		return Promise.resolve(normalizedPayload);
	}
});
```

**Comment by mtheoryx** [comment]
Great! I'll give that a shot.

Also, does your new memory adapter also have the same issue of managing all the data? I just noticed that addition when I was hunting around today.

**Comment by gordonkristan** [comment]
Yeah, the `MemoryAdapter` is the same code as the `LocalStorageAdapter` except that it stores the database in memory, so it'll suffer from the same problem. I'm sure there's a way to use them independently like you want, just not without a little modification. I'm thinking that overriding the validation might work. I'll have to look into it.

**Comment by mtheoryx** [comment]
It would definitely be useful in development, freeing up client-side advancement and experimentation from relying on either api full implementation, or "faking" server responses, which can be a significant time expense in itself.

**Comment by mtheoryx** [comment]
Just to follow up, your suggestion for extending the Adapter itself is working great, thanks so much!
